name: 'Rebol-BlurHash CI'
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 32bit Rebol/BlurHash extension
      run: ./siskin Rebol-BlurHash.nest --msvc blurhash-windows-x86

    - name: Prepare 32bit Rebol/BlurHash extension
      run:  MOVE ./msvc/Release-Win32/blurhash-windows-x86.dll ./blurhash-windows-x86.rebx

    - name: Build 64bit Rebol/BlurHash extension
      run: ./siskin Rebol-BlurHash.nest --msvc blurhash-windows-x64

    - name: Prepare 64bit Rebol/BlurHash extension
      run:  MOVE ./msvc/Release-x64/blurhash-windows-x64.dll ./blurhash-windows-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0
      with:
        product: Bulk

    - name: Minimal Rebol/BlurHash extension test
      run:  ./rebol3 ci-test.r3

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-BlurHash-CI-windows-${{github.run_id}}
        path: ./*.rebx

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 64bit Rebol/BlurHash extension
      run: ./siskin Rebol-BlurHash.nest --clean blurhash-linux-x64

    - name: Prepare 64bit Rebol BlurHash extension
      run:  mv ./build/blurhash-linux-x64.so ./blurhash-linux-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0
      with:
        product: Bulk

    - name: Minimal Rebol/BlurHash extension test
      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol/BlurHash extension
      run:  gzip -9 ./blurhash-linux-x64.rebx

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-BlurHash-CI-linux-${{github.run_id}}
        path: ./*.gz

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Siskin Builder
      uses: oldes/install-siskin@v0.17.0

    - name: Build 64bit Rebol/BlurHash extension
      run: ./siskin Rebol-BlurHash.nest blurhash-macos-x64

    - name: Prepare 64bit Rebol BlurHash extension
      run:  mv ./build/blurhash-macos-x64.dylib ./blurhash-macos-x64.rebx

    - name: Install Rebol for extension test
      uses: oldes/install-rebol@v3.18.0
      with:
        product: Bulk

    - name: Minimal Rebol/BlurHash extension test
      run:  ./rebol3 ci-test.r3

    - name: Compress 64bit Rebol/BlurHash extension
      run:  gzip -9 ./blurhash-macos-x64.rebx

    - uses: actions/upload-artifact@v4
      with:
        name: Rebol-BlurHash-CI-macos-${{github.run_id}}
        path: ./*.gz

#  Haiku-x86:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Download Haiku Rebol-dev container
#        run: docker pull docker.io/oldes/rebol-dev:haiku-x86
#
#      - name: Build all Rebol/BlurHash for Haiku OS x86
#        run: docker run --rm -v $PWD:/siskin oldes/rebol-dev:haiku-x86 bash -c 'cd /siskin; rebol siskin.r3 Rebol-BlurHash.nest blurhash-haiku-x86'
#
#      - name: Compress result before uploading
#        run: |
#          sudo mv ./build/blurhash-haiku-x86.so ./blurhash-haiku-x86.rebx
#          sudo gzip -9 ./blurhash-haiku-x86.rebx
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Rebol-BlurHash-CI-${{github.run_id}}
#          path: ./blurhash-*.gz
#
#  Haiku-x64:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Download Haiku Rebol-dev container
#        run: docker pull docker.io/oldes/rebol-dev:haiku-x64
#
#      - name: Build all Rebol/BlurHash for Haiku OS x64
#        run: docker run --rm -v $PWD:/siskin oldes/rebol-dev:haiku-x64 bash -c 'cd /siskin; rebol siskin.r3 Rebol-BlurHash.nest blurhash-haiku-x64'
#
#      - name: Compress result before uploading
#        run: |
#          sudo mv ./build/blurhash-haiku-x64.so ./blurhash-haiku-x64.rebx
#          sudo gzip -9 ./blurhash-haiku-x64.rebx
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: Rebol-BlurHash-CI-${{github.run_id}}
#          path: ./blurhash-*.gz
#
#